name: 'approval by labels'
description: 'approvals triggered by labels'
inputs:
  github-token:
    description: github access token
    required: false
    default: ${{ github.token }}
  valid-approval-teams:
    description: valid approval teams
    required: true
  expected-label-name:
    description: expected label name
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
